// ==============================================
// DATOS DE ACTRICES GL
// Compartido entre actrices-gl.html (fichas) e index.html (aviso de cumpleaños)
// 👉 Para agregar una actriz nueva: copiá un bloque { ... } completo,
// pegalo antes del corchete de cierre "]" y completá sus datos.
// Campos opcionales (si no los tenés, no pongas la línea y no pasa nada):
// nombreNativo, nacimiento, nacionalidad, instagram, ship, shipSlug, bio, mascota, agencia
// ==============================================
const actricesArray = [
  {
    nombre: "Alisa Khemnak",
    slug: "alisa-khemnak-gl-actriz",
    nombreNativo: "อลิสา เขมนาค",
    nacionalidad: "Tailandesa",
    nacimiento: "1996-07-17",
    foto: "/img/actrices/alisa-khemnak.jpg",
    instagram: "https://www.instagram.com/nm.alisa",
    ship: "NamoAmee",
    series: ["Ice Break, Heart Melt (2025)"],
  },
  {
    nombre: "Anda Anunta Teavirat",
    slug: "anda-anunta-teavirat-gl-actriz",
    nombreNativo: "อันดา อนันตา เตียวิรัตน์",
    nacionalidad: "Tailandesa",
    nacimiento: "1998-04-10",
    foto: "/img/actrices/anda-anunta-teavirat.jpg",
    instagram: "https://www.instagram.com/anda_anunta",
    ship: "AndaLookkaew",
    shipSlug: "andalookkaew-gl-ship",
    series: [
    
      "Love Senior (2023)",
   
      "Khom Khlang (2026)",
      "Remain (2026)",
    ],
  },
  {
    nombre: "Aom Pundao Panyabaramee",
    slug: "aom-pundao-panyabaramee-gl-actriz",
    nombreNativo: "ออม พันดาว ปัญญาบารมี",
    nacionalidad: "Tailandesa",
    nacimiento: "1999-06-18",
    foto: "/img/actrices/aom-pundao-panyabaramee.jpg",
    instagram: "https://www.instagram.com/_pundao",
    ship: "ShellyPundao",
    shipSlug: "shellypundao-gl-ship",
    series: ["Roller Coaster The Series (2025)", "By Your Side (2026)"],
  },
  {
    nombre: "Aoom Thaweeporn Phingchamrat",
    slug: "aoom-thaweeporn-phingchamrat-gl-actriz",
    nombreNativo: "อุ้ม ทวีพร พริ้งจำรัส",
    nacionalidad: "Tailandesa",
    nacimiento: "1996-03-17",
    foto: "/img/actrices/aoom-thaweeporn-phingchamrat.jpg",
    instagram: "https://www.instagram.com/aoomtwp",
    ship: "MeenBabe",
    shipSlug: "meenbabe-gl-ship",
    series: [
      "Delete Your Past (2024)",
      "Under Her Rules (2025)",
      "About Galaxy (2026)",
    ],
  },
  {
    nombre: "Apple Lapisara Intarasut",
    slug: "apple-lapisara-intarasut-gl-actriz",
    nombreNativo: "แอปเปิ้ล ลาภิสรา อินทรสูต",
    nacionalidad: "Tailandesa",
    nacimiento: "1994-09-01",
    foto: "/img/actrices/apple-lapisara-intarasut.jpg",
    instagram: "https://www.instagram.com/applelapisara",
    ship: "AppleMim",
    shipSlug: "applemim-gl-ship",
    series: ["4 Elements: The Earth (2026), 4 Elements: The Fire (2026), 4 Elements: The Water (2026), 4 Elements: The Air (2026)",
    "Somewhere Somehow  (2025)"],
  },
  {
    nombre: "Arhoung Nattawadee Pipobpornchai",
    slug: "arhoung-nattawadee-pipobpornchai-gl-actriz",
    nombreNativo: " อาฮ๋วง ณัฐวดี พิภพพรชัย",
    nacionalidad: "Tailandesa",
    nacimiento: "2004-09-05",
    foto: "/img/actrices/arhoung-nattawadee-pipobpornchai.jpg",
    instagram: "https://www.instagram.com/arhoungg",
    ship: "PamArhoung",
    shipSlug: "Pamy-Arhoung-gl-ship",
    series: ["Love of Secret (2022)", "Queendom (2025)"],
  },
  {
    nombre: "Arling Angsumalee Inchai",
    slug: "arling-angsumalee-inchai-gl-actriz",
    nombreNativo: "อาหลิง อังศุมาลี อินทร์ฉาย",
    nacionalidad: "Tailandesa",
    nacimiento: "2004-01-15",
    foto: "/img/actrices/arling-angsumalee-inchai.jpg",
    instagram: "https://www.instagram.com/_axling",
    ship: "ArlingKitty",
    series: [
    "Why Even Try (2026)",
    "Beloved Frangipani (2026)",
      "Love Beyond the Fence (2025)",
      "Can I Love You, Ms. Cold? (2025)",
     
      "Doctor Love Edition (2025)",
      "Heart Rule (2025)",
      "Killer Heart (2025)",
      "My Dear Ghost (2025)",
      "L.L.L. Project (2025)"
    ],
  },
  {
    nombre: "Atom Aphichaya Kamnoetsirikun",
    slug: "atom-aphichaya-kamnoetsirikun-gl-actriz",
    nombreNativo: "อะตอม อภิชญา กำเนิดศิริกุล",
    nacionalidad: "Tailandesa",
    nacimiento: "1997-11-20",
    foto: "/img/actrices/atom-aphichaya-kamnoetsirikun.jpg",
    instagram: "https://www.instagram.com/atomapcy_",
    ship: "AtomMer",
    shipSlug: "atommer-gl-ship",
    series: ["Love Senior (2023)", "My Only Sunshine (2025)"],
  },
  {
    nombre: "Atom Pariya Piyapanopas",
    slug: "atom-pariya-piyapanopas-gl-actriz",
    nombreNativo: "อะตอม ปริยะ ปิยะพันธ์โอภาส",
    nacionalidad: "Tailandesa",
    nacimiento: "2001-11-13",
    foto: "/img/actrices/atom-pariya-piyapanopas.jpg",
    instagram: "https://www.instagram.com/atomprys",
    ship: "FayeAtom",
    shipSlug: "fayeatom-gl-ship",
    series: ["Broken of Love (2026)"],
  },
  {
    nombre: "Aya Orapan Phongmaykin",
    slug: "aya-orapan-phongmaykin-gl-actriz",
    nombreNativo: "เอญ่า อรพรรณ ผ่องเมฆินทร์",
    nacionalidad: "Tailandesa",
    nacimiento: "2000-02-21",
    foto: "/img/actrices/aya-orapan-phongmaykin.jpg",
    instagram: "https://www.instagram.com/ayaorapan",
    ship: "MieAya",
    shipSlug: "MieAya-gl-ship",
    series: ["Love Beyond Dreams (2026)"],
  },
  {
    nombre: "Azura Belva Emma Denise",
    slug: "azura-belva-emma-denise-gl-actriz",
    // nombreNativo: no confirmado
    // nacionalidad: no confirmada
    // nacimiento: no confirmada
    foto: "/img/actrices/azura-belva-emma-denise.jpg",
    instagram: "https://www.instagram.com/bxellaq",
    ship: "AizeBella",
    series: ["Teach Me Softly (2025)", "The Girl Who Meow (2025)"],
  },
  {
    nombre: "Becky Rebecca Patricia Armstrong",
    slug: "becky-gl-actriz",
    nombreNativo: "เบคกี้ รีเบคก้า แพทรีเซีย อาร์มสตรอง",
    nacionalidad: "Tailandesa-británica",
    nacimiento: "2002-12-05",
    foto: "/img/actrices/becky.jpg",
    instagram: "https://www.instagram.com/beccca",
    ship: "FreenBecky",
    shipSlug: "freenbecky-gl-ship",
    series: [
      "GAP: The Series (2022)",
      "Uranus 2324 (2024)",
      "The Loyal Pin (2024)",
      "4 Elements: The Air (2026)",
      "4 Elements: The Fire (2026)",
    ],
  },
  {
    nombre: "Belle Jiratchaya Kittavornsakul",
    slug: "belle-jiratchaya-kittavornsakul-gl-actriz",
    nombreNativo: "เบลเล่ จิรัชญา กิจถาวรสกุล",
    nacionalidad: "Tailandesa",
    nacimiento: "2005-05-01",
    foto: "/img/actrices/belle-jiratchaya-kittavornsakul.jpg",
    instagram: "https://www.instagram.com/bellejirat",
    ship: "LillyBelle",
    shipSlug: "lillybelle-gl-ship",
    series: ["Harmony Secret (2025)", "I Wanna Be Sup'tar (2026)"],
  },
  {
    nombre: "Bonnie Pattraphus Borattasuwan",
    slug: "bonnie-pattraphus-borattasuwan-gl-actriz",
    nombreNativo: "บอนนี่ ภัทราภัสร์ โบรัชตะสุวรรณ์",
    nacionalidad: "Tailandesa",
    nacimiento: "2004-01-27",
    foto: "/img/actrices/bonnie-pattraphus-borattasuwan.jpg",
    instagram: "https://www.instagram.com/beonnnie",
    ship: "EmiBonnie",
    shipSlug: "emibonnie-gl-ship",
    series: ["Us (2025)", "Girl Rules (2026)","Moonshadow (2026)"],
  },
  {
    nombre: "Chanya Amarit Duval",
    slug: "chanya-amarit-duval-gl-actriz",
    nombreNativo: "ชัญญา อมฤต ดูวาล์",
    nacionalidad: "Tailandesa-francesa",
    nacimiento: "1996-08-11",
    foto: "/img/actrices/chanya-amarit-duval.jpg",
    instagram: "https://www.instagram.com/chanyaduval",
    ship: "MyChan",
    series: ["AI Girl (2026)"],
  },
  {
    nombre: "Charlotte Austin",
    slug: "charlotte-austin-gl-actriz",
    nombreNativo: "ชาล็อต ออสติน",
    nacionalidad: "Tailandesa-británica",
    nacimiento: "1998-12-21",
    foto: "/img/actrices/charlotte-austin.jpg",
    instagram: "https://www.instagram.com/itscharlotty",
    ship: "EngLot",
    shipSlug: "englot-gl-ship",
    series: [
      "Show Me Love (2023)",
      "Love Bully (2024)",
      "Petrichor (2024)",
      "Unlimited Love (2025)",
      "4 Elements: The Water (2026)",
    ],
  },
  {
    nombre: "Chayissara Wattananawin",
    slug: "chayissara-wattananawin-gl-actriz",
    nombreNativo: "เจนนี่ ชยิสรา วัฒนะนาวิน",
    nacionalidad: "Tailandesa",
    nacimiento: "1998-04-02",
    foto: "/img/actrices/chayissara-wattananawin.jpg",
    instagram: "https://www.instagram.com/jennychayissara",
    series: ["When Love Returns (2026)"],
  },
  {
    nombre: "Christine Gulasatree Michalsky",
    slug: "christine-gulasatree-michalsky-gl-actriz",
    nombreNativo: "คริสติน กุลสตรี มิชารัลสกี้",
    nacionalidad: "Tailandesa",
    nacimiento: "1995-09-10",
    foto: "/img/actrices/christine-gulasatree-michalsky.jpg",
    instagram: "https://www.instagram.com/gulasatree",
    ship: "ChristineMae",
    shipSlug: "christinemae-gl-ship",
    series: ["Reverse 4 You (2024)"],
  },
  {
    nombre: "Chutikan Siangdee",
    slug: "chutikan-siangdee-gl-actriz",
    nombreNativo: "ไอซ์ ชุติกาญจน์ เสียง",
    nacionalidad: "Tailandesa",
    nacimiento: "2001",
    foto: "/img/actrices/chutikan-siangdee.jpg",
    instagram: "https://www.instagram.com/ice_chu_",
    series: [
      "Fate's Whispers (2024)",
      "Love From Another Star (2025)",
      "Hate You Love You (2025)",
      "L.L.L. Project (2025)",
      "Dear Diary (2025)",
      "Taste of Her (2025)",
      "The End (2025)",
    ],
  },
  {
    nombre: "Ciize Rutricha Phapakithi",
    slug: "ciize-rutricha-phapakithi-gl-actriz",
    nombreNativo: "ไซซี รัตท์ริชา ประภากิติ",
    nacionalidad: "Tailandesa",
    nacimiento: "1999-09-23",
    foto: "/img/actrices/ciize-rutricha-phapakithi.jpg",
    instagram: "https://www.instagram.com/ciizezphr",
    ship: "KapookCiize / EarnCiize",
    shipSlug: "kapook-ciize-gl-ship",
    series: [
      "23.5 (2024)",
      "Pluto (2024)",
      "Girl Rules (2026)",
      "Enemies with Benefits (2026)",
      "Ditto (2026)",
    ],
  },
  {
    nombre: "Darran Zeththinich Chanavarasutthisiri",
    slug: "darran-zeththinich-chanavarasutthisiri-gl-actriz",
    nombreNativo: "ดารัณ เศรษฐิณิช ชนวราสุทธิศิริ",
    nacionalidad: "Tailandesa",
    nacimiento: "1993-09-22",
    foto: "/img/actrices/darran-zeththinich-chanavarasutthisiri.jpg",
    instagram: "https://www.instagram.com/darranzeth",
    ship: "JaraJennie",
    series: ["Dream Mind"],
  },
  {
    nombre: "Nur Desoraya Techapaibul",
    slug: "desoraya-techapaibul-gl-actriz",
    nombreNativo: "เหนือ ดิสรยา เตชะไพบูลย์",
    nacionalidad: "Tailandesa",
    nacimiento: "2000-12-09",
    foto: "/img/actrices/desoraya-techapaibul.jpg",
    instagram: "https://www.instagram.com/nurdesoraya",
    series: ["Dangerous Queen (2025)"],
  },
  {
    nombre: "Earn Preeyaphat Lawsuwansiri",
    slug: "earn-preeyaphat-lawsuwansiri-gl-actriz",
    nombreNativo: "เอิร์น ปรียาภัทย์ หล่อสุวรรณศิริ",
    nacionalidad: "Tailandesa",
    nacimiento: "2001-12-30",
    foto: "/img/actrices/earn-preeyaphat-lawsuwansiri.jpg",
    instagram: "https://www.instagram.com/earnpypp_",
    ship: "EarnCiize",
    series: ["23.5 (2024)", "Pluto (2024)"],
  },
  {
    nombre: "Oom Eisaya Hosuwan",
    slug: "eisaya-hosuwan-gl-actriz",
    nombreNativo: "อุ้ม อิษยา ฮอสุวรรณ",
    nacionalidad: "Tailandesa",
    nacimiento: "1996-07-04",
    foto: "/img/actrices/eisaya-hosuwan.jpg",
    instagram: "https://www.instagram.com/oomeisaya",
    ship: "OomBam",
    shipSlug: "oombam-gl-ship",
    series: ["Play Park (2026)", "Fulfill (2026)"],
  },
  {
    nombre: "Ella Neelasha Dorling",
    slug: "ella-neelasha-gl-actriz",
    nombreNativo: "เอล่า นีรชา ดอร์ลิ่ง",
    nacionalidad: "Tailandesa",
    nacimiento: "2003-08-07",
    foto: "/img/actrices/ella-neelasha.jpg",
    instagram: "https://www.instagram.com/niirchaa_46",
    series: ["When Love Returns (2026)"],
  },
  {
    nombre: "Emi Thasorn Klinnium",
    slug: "emi-thasorn-klinnium-gl-actriz",
    nombreNativo: "เอมี่ ทสร กลิ่นเนียม",
    nacionalidad: "Tailandesa,China",
    nacimiento: "1998-04-25",
    foto: "/img/actrices/emi-thasorn-klinnium.jpg",
    instagram: "https://www.instagram.com/emiamily",
    ship: "EmiBonnie",
    shipSlug: "emibonnie-gl-ship",
    series: ["Us (2025)","Girls Rules (2026)", "Moonshadow (2026)"],
  },
  {
    nombre: "Engfa Waraha",
    slug: "engfa-waraha-gl-actriz",
    nombreNativo: "อิงฟ้า วราหะ",
    nacionalidad: "Tailandesa",
    nacimiento: "1995-02-15",
    foto: "/img/actrices/engfa-waraha.jpg",
    instagram: "https://www.instagram.com/fa_engfa8",
    ship: "EngLot",
    shipSlug: "englot-gl-ship",
    series: [
      "Show Me Love (2023)",
      "Love Bully (2024)",
      "Petrichor (2024)",
      "Unlimited Love (2025)",
      "4 Elements: The Earth (2026)",
      "4 Elements: The Water (2026)",
      "4 Elements: The Air (2026)",
      "4 Elements: The Fire (2026)",
      "Under Her Rules (2026)",
    ],
  },
  {
    nombre: "England Ladamanee Rattanapornvareesakul",
    slug: "england-ladamanee-rattanapornvareesakul-gl-actriz",
    nombreNativo: "อิ๊งแลนด์ ลดามณี รัตนพรวารีสกุล",
    nacionalidad: "Tailandesa",
    nacimiento: "2004-08-04",
    foto: "/img/actrices/england-ladamanee-rattanapornvareesakul.jpg",
    instagram: "https://www.instagram.com/eng_lr39",
    ship: "NikyEngland",
    shipSlug: "nikyengland-gl-ship",
    series: ["Shades (2026)"],
  },
  {
    nombre: "Enjoy Thidarat Puerthong",
    slug: "enjoy-thidarat-puerthong-gl-actriz",
    nombreNativo: "เอ็นจอย ธิดารัตน์ ปรือทอง",
    nacionalidad: "Tailandesa",
    nacimiento: "1997-10-13",
    foto: "/img/actrices/enjoy-thidarat-puerthong.jpg",
    instagram: "https://www.instagram.com/enjoyyotdr",
    ship: "EnjoyJune",
    shipSlug: "enjoyjune-gl-ship",
    series: ["Denied Love (2025)"],
  },
  {
    nombre: "Fahsai Minyada Boonsup",
    slug: "fahsai-minyada-boonsup-gl-actriz",
    nombreNativo: "ฟ้าใส มิญญาดา บุญทรัพย์",
    nacionalidad: "Tailandesa",
    nacimiento: "1995-08-19",
    foto: "/img/actrices/fahsai-minyada-boonsup.jpg",
    instagram: "https://www.instagram.com/fahsai.myd",
    ship: "Fern & Fahsai",
    series: ["Be Mine: Prologue Day (2023)"],
  },
  {
    nombre: "Fahsai Paweensuda Drouin",
    slug: "fahsai-paweensuda-drouin-gl-actriz",
    nombreNativo: "ฟ้าใส ปวีณสุดา ดรูอิ้น",
    nacionalidad: "Tailandesa-canadiense",
    nacimiento: "1993-10-12",
    foto: "/img/actrices/fahsai-paweensuda-drouin.jpg",
    instagram: "https://www.instagram.com/paweensuda",
    series: ["The Hidden Blood (2026)"],
  },
  {
    nombre: "Fay Apisara Lertwisettheerakul",
    slug: "fay-apisara-lertwisettheerakul-gl-actriz",
    nombreNativo: "เฟย์ อภิสรา เลิศวิเศษธีรกุล",
    nacionalidad: "Tailandesa",
    nacimiento: "1999-12-08",
    foto: "/img/actrices/fay-apisara-lertwisettheerakul.jpg",
    instagram: "https://www.instagram.com/fayapis.l",
    ship: "FayGene",
    series: ["I Wanna Be Sup'tar (2026)", "Chasing Love (2026)"],
  },
  {
    nombre: "Fay Kanyapat",
    slug: "fay-kunyaphat-na-nakorn-gl-actriz",
    nombreNativo: "เฟย์ กัญญาพัชร ณ นคร",
    nacionalidad: "Tailandesa",
    nacimiento: "2001-12-02",
    foto: "/img/actrices/fay-kunyaphat-na-nakorn.jpg",
    instagram: "https://www.instagram.com/fay_riezz",
    ship: "FayMay",
    shipSlug: "faymay-gl-ship",
    series: [
      "My Marvellous Dream Is You (2024)",
      "Somewhere Somehow (2025)",
    ],
  },
  {
    nombre: "Faye Peraya Malisorn",
    slug: "faye-peraya-malisorn-gl-actriz",
    nombreNativo: "ฝ้าย พีรญา มะลิซ้อน",
    nacionalidad: "Tailandesa",
    nacimiento: "1994-10-14",
    foto: "/img/actrices/faye-peraya-malisorn.jpg",
    instagram: "https://www.instagram.com/faye",
    ship: "FayeAtom / FayeYoko",
    shipSlug: "fayeatom-gl-ship",
    series: [
      "Blank The Series (2024)",
      "Blank The Series Season 2 (2024)",
      "Broken of Love (2026)",
    ],
  },
  {
    nombre: "FayFay Thitayaporn Prasertsom",
    slug: "fayfay-thitayaporn-prasertsom-gl-actriz",
    nombreNativo: "เฟย์เฟย์ ฑิตยาพร ประเสริฐสม",
    nacionalidad: "Tailandesa",
    nacimiento: "¿?-01-12",
    foto: "/img/actrices/fayfay-thitayaporn-prasertsom.jpg",
    instagram: "https://www.instagram.com/f.fayfayy",
    ship: "FayFay",
    series: ["B•Friend (2025)"],
   
  },
  {
    nombre: "Weerin Kaewpuk Ferin",
    slug: "ferin-weerin-kaewpuk-gl-actriz",
    nombreNativo: "เฟริน วีรินท์ แก้วปุก",
    nacionalidad: "Tailandesa",
    nacimiento: "1994-12-07",
    foto: "/img/actrices/ferin-weerin-kaewpuk.jpg",
    instagram: "https://www.instagram.com/ferinweerin",
    ship: "FerinPuiFai / Feringreat",
    series: [
      "Same Place, New Pace (2025)",
      "Hidden Heat (2025)",
      "Catch Cat Crush (2025)",
      "Sassy Season (2025)",
      "Hidden Half (2025)",
      "I Don't Remember the Feeling (2025)",
      "Girl Rules (2026)",
    ],
  },
  {
    nombre: "Fern Jeerawan Kumjina",
    slug: "fern-jeerawan-kumjina-gl-actriz",
    nombreNativo: "เฟิร์น จีรวรรณ คำจินะ",
    nacionalidad: "Tailandesa",
    nacimiento: "1996-11-27",
    foto: "/img/actrices/fern-jeerawan-kumjina.jpg",
    ship: "Fern & Fahsai",
    series: ["Be Mine: Prologue Day (2023)"],
  },
  {
    nombre: "Film Rachanun Mahawan",
    slug: "film-rachanun-mahawan-gl-actriz",
    nombreNativo: "ฟิล์ม รชานันท์ มหาวรรณ์",
    nacionalidad: "Tailandesa",
    nacimiento: "2000-07-14",
    foto: "/img/actrices/film-rachanun-mahawan.jpg",
    instagram: "https://www.instagram.com/fr.racha",
    ship: "NamtanFilm",
    shipSlug: "namtanfilm-gl-ship",
    series: [
      "Pluto (2024)",
      "Girl Rules (2026)",
      "Moonshadow (2026)",
      "Her (2026)",
    ],
  },
  {
    nombre: "Folk Sutima Kokiatwanit",
    slug: "folk-sutima-korkiatvanich-gl-actriz",
    nombreNativo: "โฟล์ค สุธิมา ก่อเกียรติวนิช",
    nacionalidad: "Tailandesa",
    nacimiento: "2000-05-16",
    foto: "/img/actrices/folk-sutima-korkiatvanich.jpg",
    instagram: "https://www.instagram.com/ffolky",
    ship: "OrmFolk",
    shipSlug: "ormfolk-gl-ship",
    series: [
      "Be Mine: Prologue Day (2023)",
      "Apple My Love (2024)",
      "(Your) Apple (2025)",
      "My Lady's Bodyguard (2026)",
      "Love Bound (2026)",
      "CRUSH (2026)",
    ],
  },
  {
    nombre: "Fond Natticha Chantaravareelekha",
    slug: "fond-natticha-chantaravareelekha-gl-actriz",
    nombreNativo: "ฟ้อนด์ ณัฐทิชา จันทรวารีเลขา",
    nacionalidad: "Tailandesa",
    nacimiento: "2002-12-03",
    foto: "/img/actrices/fond-natticha-chantaravareelekha.jpg",
    instagram: "https://www.instagram.com/fondnatticha",
    ship: "PahnFond",
    series: ["The Cheese Sisters (2022)", "Wish Upon a Star (2026)"],
  },
  {
    nombre: "Freen Sarocha Chankimha",
    slug: "freen-sarocha-chankimha-gl-actriz",
    nombreNativo: "ฟรีน สโรชา จันทร์กิมฮะ",
    nacionalidad: "Tailandesa",
    nacimiento: "1998-08-08",
    foto: "/img/actrices/freen-sarocha-chankimha.jpg",
    instagram: "https://www.instagram.com/srchafreen",
    ship: "FreenBecky",
    shipSlug: "freenbecky-gl-ship",
    series: [
      "GAP: The Series (2022)",
      "Uranus 2324 (2024)",
      "The Loyal Pin (2024)",
      "4 Elements: The Earth (2026)",
      "4 Elements: The Water (2026)",
      "4 Elements: The Air (2026)",
      "4 Elements: The Fire (2026)",
      "Cranium (2026)",
    ],
  },
  {
    nombre: "Eang Ganchutikan Pytanagul",
    slug: "ganchutikan-pytanagul-gl-actriz",
    nombreNativo: "เอิง กัญชุติกาญจน์ พีร์ธนัทกุล",
    nacionalidad: "Tailandesa",
    // nacimiento: no confirmada
    foto: "/img/actrices/ganchutikan-pytanagul.jpg",
    instagram: "https://www.instagram.com/ganchu_erng",
    series: [
      "Stay with Me (2024)",
      "Stay with Me Season 2 (2025)",
      "Stay with Me Season 3 (2025)",
      "Stay with Me Season 4 (2025)",
    ],
  },
  {
    nombre: "Gene Ornalin",
    slug: "gene-ornalin-leelaburanathanakul-gl-actriz",
    nombreNativo: "จีนี่ อรนลิน ลีลาบูรณธนกูร",
    nacionalidad: "Tailandesa",
    nacimiento: "2002-03-10",
    foto: "/img/actrices/gene-ornalin-leelaburanathanakul.jpg",
    instagram: "https://www.instagram.com/ornalin_gene",
    ship: "FayGene",
    series: ["I Wanna Be Sup'tar (2026)", "Chasing Love (2026)"],
  },
  {
    nombre: "Gift Sirinart Sugandharat",
    slug: "gift-sirinart-sugandharat-gl-actriz",
    nombreNativo: "กิ๊ฟ สิรินาถ สุคันธรัต",
    nacionalidad: "Tailandesa",
    nacimiento: "1995-10-10",
    foto: "/img/actrices/gift-sirinart-sugandharat.jpg",
    instagram: "https://www.instagram.com/siin.41",
    ship: "GiftAomsin",
    series: ["Love Bully (2024)", "Chasing Love (2026)"],
  },
  {
    nombre: "Ginny Natnicha Pratipnatsiri",
    slug: "ginny-natnicha-pratipnatsiri-gl-actriz",
    nombreNativo: "จินนี่ ณัฐณิชา ประทีปนาฏศิริ",
    nacionalidad: "Tailandesa",
    nacimiento: "2000-12-17",
    foto: "/img/actrices/ginny-natnicha-pratipnatsiri.jpg",
    instagram: "https://www.instagram.com/ginnynatnicha",
    ship: "GinnyJayna",
    shipSlug: "ginnyjayna-gl-ship",
    series: ["Poisonous Love (2025)", "Lunar Secret (2026)"],
   
  },
  {
    nombre: "Grace Budsarin",
    slug: "grace-budsarin-wonglelanont-gl-actriz",
    // nombreNativo: no confirmado
    nacionalidad: "Tailandesa",
    nacimiento: "1997-09-21",
    foto: "/img/actrices/grace-budsarin-wonglelanont.jpg",
    ship: "GraceOaey",
    series: ["Mate (2024)"],
  },
  {
    nombre: "Grace Harper",
    slug: "grace-harper-gl-actriz",
    // nombreNativo: no confirmado
    // nacionalidad: no confirmada
    nacimiento: "1998-04-19",
    foto: "/img/actrices/grace-harper.jpg",
    instagram: "https://www.instagram.com/thegraceharperr",
    series: ["Player (2025)"],
  },
  {
    nombre: "Gunya Sirigunya",
    slug: "gunya-sirigunya-khamkoon-gl-actriz",
    nombreNativo: "กัญญา สิริกัญญา ค้ำคูณ",
    nacionalidad: "Tailandesa",
    // nacimiento: no confirmada
    foto: "/img/actrices/gunya-sirigunya-khamkoon.jpg",
    instagram: "https://www.instagram.com/Gunya_sirigunya",
    ship: "GunyaJennie",
    series: [
      "My Little Miss (2025)",
      "My Stepsister (2025)",
      "Friends (2025)",
      "You're My Gift (2025)",
      "Kiss of Yesterday (2025)",
    ],
  },
  {
    nombre: "Ice Papichaya",
    slug: "ice-papichaya-pattaralikitsakul-gl-actriz",
    // nombreNativo: no confirmado
    nacionalidad: "Tailandesa",
    nacimiento: "1998-07-04",
    foto: "/img/actrices/ice-papichaya-pattaralikitsakul.jpg",
    series: [],
  },
  {
    nombre: "Idea Natnapin",
    slug: "idea-natnapin-soontornjirakarn-gl-actriz",
    // nombreNativo: no confirmado
    nacionalidad: "Tailandesa",
    nacimiento: "2001-10-11",
    foto: "/img/actrices/idea-natnapin-soontornjirakarn.jpg",
    instagram: "https://www.instagram.com/iideapinz",
    series: ["Trial Love (próximamente)"],
  },
  {
    nombre: "Jamie Juthapich",
    slug: "jamie-juthapich-indrajundra-gl-actriz",
    nombreNativo: "จุฑาพิชญ์ อินทร์จันทร์",
    nacionalidad: "Tailandesa",
    nacimiento: "1997-12-11",
    foto: "/img/actrices/jamie-juthapich-indrajundra.jpg",
    series: [
      "Pluto (2024–2025)",
      "Enemies with Benefits (2026)",
      "Moonshadow (2026)",
    ],
  },
  {
    nombre: "Jan Ployshompoo",
    slug: "jan-ployshompoo-supasap-gl-actriz",
    nombreNativo: "พลอยชมพู ศุภทรัพย์",
    nacionalidad: "Tailandesa",
    nacimiento: "1995-01-04",
    foto: "/img/actrices/jan-ployshompoo-supasap.jpg",
    instagram: "https://www.instagram.com/janhae",
    ship: "JanJingJing",
    series: [
      "MuTe / Luv: Hello, Is This Luck? (2025)",
      "Enemies with Benefits (2026)",
      "Bake Love Feeling (2026)",
    ],
  },
  {
    nombre: "Jane Methika",
    slug: "jane-methika-jiranorraphat-gl-actriz",
    // nombreNativo: no confirmado
    nacionalidad: "Tailandesa-taiwanesa",
    nacimiento: "1999-06-18",
    foto: "/img/actrices/jane-methika-jiranorraphat.jpg",
    instagram: "https://www.instagram.com/janeeyeh",
    ship: "KaoJane",
    series: ["Love Design (2025)"],
  },
  {
    nombre: "Jayna Angelina",
    slug: "jayna-angelina-stevens-gl-actriz",
    // nombreNativo: no confirmado
    nacionalidad: "Tailandesa-estadounidense",
    nacimiento: "2006-02-16",
    foto: "/img/actrices/jayna-angelina-stevens.jpg",
    instagram: "https://www.instagram.com/aangelinaa.ss",
    ship: "GinnyJayna",
    shipSlug: "ginnyjayna-gl-ship",
    series: ["Poisonous Love (2025)", "Lunar Secret (2026)"],
  },
  {
    nombre: "Jennie Jane",
    slug: "jennie-jane-gl-actriz",
    // nombreNativo: no confirmado
    nacionalidad: "Tailandesa",
    nacimiento: "2004-09-09",
    foto: "/img/actrices/jennie-jane.jpg",
    ship: "GunyaJennie",
    series: [
      "My Stepsister (2025)",
      "Friends (2025)",
      "You're My Gift (2025)",
      "Kiss of Yesterday (2025)",
    ],
  },
  {
    nombre: "Jessie Natsiya",
    slug: "jessie-natsiya-prommart-gl-actriz",
    // nombreNativo: no confirmado
    nacionalidad: "Tailandesa",
    nacimiento: "2001-03-29",
    foto: "/img/actrices/jessie-natsiya-prommart.jpg",
    instagram: "https://www.instagram.com/jessienatsiya.p",
    ship: "TungPangJessie",
    series: ["Heart Code (2025)", "Love in Bloom (2025)"],
  },
  {
    nombre: "JingJing Prariyapit",
    slug: "jingjing-prariyapit-yu-gl-actriz",
    // nombreNativo: no confirmado
    nacionalidad: "Tailandesa",
    nacimiento: "1997-03-31",
    foto: "/img/actrices/jingjing-prariyapit-yu.jpg",
    instagram: "https://www.instagram.com/jingjingyu36",
    ship: "JanJingJing",
    series: [
      "Whale Store xoxo (2025)",
      "MuTe / Luv: Hello, Is This Luck? (2025)",
      "Enemies with Benefits (2026)",
      "Bake Love Feeling (2026)",
    ],
  },
  {
    nombre: "Jiratchaya Komontut",
    slug: "jiratchaya-komontut-gl-actriz",
    nombreNativo: "จิรัชญา โกมลทุต",
    nacionalidad: "Tailandesa",
    nacimiento: "2003-07-22",
    foto: "/img/actrices/jiratchaya-komontut.jpg",
    instagram: "https://www.instagram.com/maybebmine",
    ship: "BmineNear",
    series: [
      "Lucky My Love (2023)",
      "Unlock Your Love (2024)",
      "Music Story: Losing Control (2025)",
      "Rental Love Lab (2026)",
    ],
  },
  {
    nombre: "June Lalida",
    slug: "june-lalida-ngamsomchat-gl-actriz",
    // nombreNativo: no confirmado
    nacionalidad: "Tailandesa",
    // nacimiento: no confirmada
    foto: "/img/actrices/june-lalida-ngamsomchat.jpg",
    instagram: "https://www.instagram.com/npjunne",
    series: ["Love Moment (2025)"],
  },
];